DynestyStatic:
  corner: true
  cornerpoints: false
  runplot: true
  traceplot: true
Emcee:
  corner: true
  likelihood_series: true
  time_series: true
  trajectories: true
PySwarmsGlobal:
  contour: true
  cost_history: true
  time_series: true
  trajectories: true
UltraNest:
  corner: true
  runplot: true
  traceplot: true
Zeus:
  corner: true
  likelihood_series: true
  time_series: true
  trajectories: true
